#An approach to count the amount of times a character appears in a string
sequence='TCTACATTACAGCCTCAAAAGTTTCACGCGGGGTTTGATCTGTAGCCCTGCCCCTAGACCCTCCGGGTACGGTTGTAGTGTCTTCTCACCACCGGGCTAGGTTCGTAATGCTTAGAAGAACGTAACTACCACGGCTGCGCCAGCAGAGATGACCAACTTGGGAAAGCGTTTCTAAGAAGATGGCGCTCATGAGTTAACATTCCCGTCTGGTATAATATGTAGGTGAGTCAGATAACAGTGGACCTCTGCGCGTACTCAATGAACTGGATGTAACCGGTATGAAGGAGCATATGGCTGAATACGGCAGGTCTATCGTCGATGCCGCTAGTATCGGTCAAAATTTTTTTGAATGGCACCTCGAAACTCGTATATTTCCAGGGCCACTTTGTCACTCCCGTCGACGGACATTCTTGTCTCCTGGGGTGATATTCCATGAGTGAGCGTATAGGACGACTGTCATGCACACCCATCACAAAGCTTTGTCAGCTAAGAAGGCTAGCGTTCCAGCGACATACGGTCGAACCCGGCGTCTTGTGGCTCGTAGACGTTGGCTCAACGAGTTTGAACTACGCGGGAGTTAACGAAGGTCTCATGCACTGCGCTACCACGGGGGATTAAGCCAATACCGGGCGAACTAGCGCTCGTTCTTGACCACTACAGACATTGTTAGGGGGCTAATGGTGGGGAGAAAACGAATCAATGTTGGATTACGGGTAGCCAATCGGCAGCACGTTCACGGCCGCCGTCTGCCCAGCAGTACATGATGGCGCCTTGGTCTACTTTGATATCACTCTGTAGTCAGCGCAGCACTAATTCGACGAACCCTCTGTGCATGTCATAATATGACGGGCA'

A = sequence.count('A')
G = sequence.count('G')
T = sequence.count('T')
C = sequence.count('C')

#Cannot concate the spaces ' ' to the variable values if they aren't converted into strings first
print(str(A)+' '+str(C)+' '+str(G)+' '+str(T))






